Homework #2 (from Vitalii Derda)
cross-development/nodejs24_hw_derdavitalii pull request #2
Opened 2024-01-28 13:04 UTC by cross-development

2024-01-28 19:28 UTC, evhenious commented on utils/logger.js
> +  const levels = {
👍

2024-01-28 19:29 UTC, evhenious commented on utils/logger.js
> +module.exports = logger().init;
🥇

2024-01-28 19:29 UTC, evhenious commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
ммммм, yarn :)

2024-01-28 19:32 UTC, evhenious requested changes
Все круто, сподобався твій підхід загалом! 
Але є одна проблемка - якщо хоч одна із env vars відсутня - код падає з помилками )) поправ це, будь ласка! (так, в описі задачі явно було сказано, що має відбутись при відсутності змінніх)

2024-01-29 06:43 UTC, cross-development commented
> Все круто, сподобався твій підхід загалом! Але є одна проблемка - якщо хоч одна із env vars відсутня - код падає з помилками )) поправ це, будь ласка! (так, в описі задачі явно було сказано, що має відбутись при відсутності змінніх)

Дякую!)
Визнаю, тестував лише відсутність значень в енв-змінних, а цей кейс із відсутністю ні. Напевне чисто через то, що зазвичай, якщо в енв.екзампл вказані змінні, то вони і вказуються в енв файлі. 
А ще буває прикол, коли змінні не передав, а аппка використовує якісь дефолтні значення не зрозуміло звідки)
В будь-якому випадку, додав дефолтні значення в конфіг.
Дякую за перевірку!

2024-01-29 08:51 UTC, evhenious commented on config/default.js
> +module.exports = {
👍

2024-01-29 08:52 UTC, evhenious approved these changes

2024-01-29 08:52 UTC, merged

2024-01-29 09:42 UTC, evhenious commented
> якісь дефолтні значення не зрозуміло звідки

Так, хаос це не прикольно, тому добре коли є щось типу центрального конфіга як у нас тут, і ти точно знаєш що всі дефолтні параметри (якщо вони є) будуть саме там :)